# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56ee191092f625f98f1eeb180ba131ed1b0b2564517433ef59680faa9e3bf74e55b5f1db5baafcc7f29a51927f08fad3d4c72d3cb228bfb50f899f1e9790f6f4

test:
  secret_key_base: 791962bcbc1ef7f444609ad4311ad35187629f3e39537df4e8e192f8b511d5fcc7b9d1e1b4bfb663af95109310451211703ec567aab4783542bbcccae664639d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
